name: Deploy PHP Application

on:
  push:
    branches:
      - master  # Adjust branch name as per your setup
  pull_request:
    branches:
      - master  # Adjust branch name as per your setup

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can choose another OS if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Deploy to server via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: '/var/www/html/'

