on:
  push:
    branches: master
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: '13.234.18.200'
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: '/var/www/html/*'
          target: '/var/www/html/'
      
      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: '13.234.18.200'
          username: 'YOUR_SSH_USERNAME'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/
            # Add your deployment commands here
