on:
  push:
    branches: master
jobs:
    deploy_job:
     runs-on: ubuntu-latest
     name: deploy
     steps:
      - name: Checkout
        uses: actions/checkout@v2      

      - name: Deploy file
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
         username: 'newftp@molniwasi.org'
         server: 'ftp.premad.in'
         port: '21'
         server-dir: '/public_html/www.premad.in/badmin/'
         password: 'newftp_250'
