on:
  push:
    paths:
      - 'badmin/testgit/*'
name: FTP Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@master
      with:
        ftp-server: 'ftp://issyway.com'
        ftp-username: 'issyway@issyway.com'
        ftp-password: 'Ishanji007@@'
        local-dir: badmin/testgit/